### ISSUE TITLE
LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.pen 

### ISSUE THREAD

**Issue by ElsayedDev** [fzyzcjy/flutter_portal#76]
When I used `TextField` widget 

the following error occurred

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.
'package:flutter/src/rendering/layer.dart':
package:flutter/…/rendering/layer.dart:1
Failed assertion: line 2502 pos 7: 'leader._lastOffset != null'

**Comment by fzyzcjy** [comment]
Please use v1.0.0 which I have fixed the bug :)

**Comment by ElsayedDev** [comment]
I already using it.
![image](https://user-images.githubusercontent.com/58011722/165944967-0f34dfad-eae1-41b4-94c7-5a2b6aa19581.png)

**Comment by fzyzcjy** [comment]
I see. Then that is bug of *flutter 2.10 stable*, which will be solved in 2.13

**Comment by fzyzcjy** [comment]
see https://github.com/fzyzcjy/flutter_portal/issues/56#issuecomment-1070959360 . Though that post is about how I fix bug of *this* repo, that post also tells you why this error message is a bug of flutter

**Comment by ElsayedDev** [comment]
Thanks

**Comment by mazino-dev** [comment]
I got something similar when I tried to compose portal-target > portal > portal-target or portal-target > portal-target.


```
════════ Exception caught by scheduler library ═════════════════════════════════
LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.
'package:flutter_portal/src/enhanced_composited_transform/flutter_src/rendering_layer.dart':
package:flutter_portal/…/flutter_src/rendering_layer.dart:1
Failed assertion: line 383 pos 7: '_debugCheckLeaderBeforeFollower(forwardLayers, inverseLayers)'
```

With some experimentation, I found a workaround for nesting level of two, not sure about higher nesting.

Use portal-target inside portal-target without any portal between them in the hierarchy and use below anchor on inner portal-target:

```
anchor: const Aligned(
    follower: Alignment.center,
    target: Alignment.center,
    alignToPortal: AxisFlag(x: true, y: true),
    portal: Alignment.center,
)
```

**Comment by fzyzcjy** [comment]
> I got something similar when I tried to compose portal-target > portal > portal-target. portal-target inside portal-target worked but inner one was in background instead of foreground.

I have had this error also when having this nest, but I have fixed it. Could you please give a reproducible sample, and ensure it fails in 1.0.0?

**Comment by ElsayedDev** [comment]
> > I got something similar when I tried to compose portal-target > portal > portal-target. portal-target inside portal-target worked but inner one was in background instead of foreground.
> 
> I have had this error also when having this nest, but I have fixed it. Could you please give a reproducible sample, and ensure it fails in 1.0.0?

I tried to change flutter channel to beta but it's still the same problem..

**Comment by fzyzcjy** [comment]
Interesting. Could you please reproducible sample, possibly by giving a github repo

**Comment by ElsayedDev** [comment]
please check this file https://github.com/ElsayedDev/errors/blob/main/portal_text_field_bug.dart

**Comment by fzyzcjy** [comment]
I see. could you please make it shorter to ease debugging

**Comment by mazino-dev** [comment]
> > I got something similar when I tried to compose portal-target > portal > portal-target. portal-target inside portal-target worked but inner one was in background instead of foreground.
> 
> I have had this error also when having this nest, but I have fixed it. Could you please give a reproducible sample, and ensure it fails in 1.0.0?

Oh, it could be me then, I was trying to do some weird stuff. I will try to untangle my codebase and reproduce the error in a new app.

**Comment by fzyzcjy** [comment]
Take your time.

**Comment by NeatFastro** [comment]
@ElsayedDev is your problem fixed? if so how? I'm facing the same issue right now myself

**Comment by NeatFastro** [comment]
Here's the minimal reproducible example.
when user taps on the TextField the the assertion fails,
the only solution  I was able to find was to comment out the assertion in the flutter sdk source code

```dart
import 'package:flutter/material.dart';
import 'package:flutter_portal/flutter_portal.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Portal(
      child: MaterialApp(
        title: 'Flutter portal layers bug',
        home: MyHomePage(title: 'Flutter Demo Home Page'),
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  bool _showPortal = false;

  void _togglePortal() {
    setState(() => _showPortal = !_showPortal);
  }

  ElevatedButton _buildPortalChild() {
    return ElevatedButton(
      onPressed: _togglePortal,
      child: const Text('Toggle portal'),
    );
  }

  Widget _buildPortalFollower() {
    return SizedBox(
      width: 400,
      height: 300,
      child: Card(
        child: Center(
          child: TextFormField(
            decoration: const InputDecoration(
              label: Text('Text form field'),
              border: OutlineInputBorder(),
            ),
          ),
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: PortalTarget(
          visible: _showPortal,
          anchor: const Aligned(
            follower: Alignment.topCenter,
            target: Alignment.bottomCenter,
          ),
          portalFollower: _buildPortalFollower(),
          child: _buildPortalChild(),
        ),
      ),
    );
  }
}
```

**Comment by NeatFastro** [comment]
environment:
  sdk: ">=2.17.0 <3.0.0"

flutter version: 3.0.0
and
flutter_portal: ^1.1.0

**Comment by fzyzcjy** [comment]
Good reproduction! So, to make reproducible sample smaller, does `_showPortal` matter here? Or can we remove that button and _showPortal logic?

**Comment by fzyzcjy** [comment]
Once it gets so simple, we can use things like https://docs.flutter.dev/testing/code-debugging `debugDumpLayerTree` etc to see what is happening (with a very small tree - clean and easy-to-debug result)

**Comment by fzyzcjy** [comment]
To fix it or make a workaround, needs to find the cause of bug, which needs a good reproducible sample :)

**Comment by NeatFastro** [comment]
> Good reproduction! So, to make reproducible sample smaller, does `_showPortal` matter here? Or can we remove that button and _showPortal logic?
> 
> Similar applies to TextFormField.decoration - can we remove it?
> 
> And TextFormField, can we use TextField. etc
> 
> And remove the Card

Nope these do not matter it was for the easier understanding of the behaviour from the user perspective

**Comment by NeatFastro** [comment]
> To fix it or make a workaround, needs to find the cause of bug, which needs a good reproducible sample :)

I might have to downgrade to flutter 2.10.x which did not had this problem, ah but now I'm using the new super param fields of the constructor, it's going to be a lot of work

**Comment by fzyzcjy** [comment]
> do you want be to simplify the code?

Yes. Simplest code possible makes it easy to debug and fix.

**Comment by NeatFastro** [comment]
> Good reproduction! So, to make reproducible sample smaller, does `_showPortal` matter here? Or can we remove that button and _showPortal logic?
> 
> Similar applies to TextFormField.decoration - can we remove it?
> 
> And TextFormField, can we use TextField. etc
> 
> And remove the Card

Here's you go.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_portal/flutter_portal.dart';

void main() => runApp(
      Portal(
        child: MaterialApp(
          home: Material(
            child: Center(
              child: PortalTarget(
                anchor: const Aligned(
                  follower: Alignment.topCenter,
                  target: Alignment.bottomCenter,
                ),
                portalFollower: SizedBox(
                  width: 400,
                  height: 300,
                  child: TextFormField(),
                ),
                child: const Text('Portal child'),
              ),
            ),
          ),
        ),
      ),
    );
```

**Comment by fzyzcjy** [comment]
Great! The next step is to add a reproducible sample in https://github.com/fzyzcjy/flutter_portal/blob/master/test/widget_test.dart. Maybe you need `pumpWidget` and `tester.tap`

**Comment by fzyzcjy** [comment]
I mean I do not see errors when using lib in my app

**Comment by NeatFastro** [comment]
hmmm but we know the error only happens when we placed a TextField widget inside the portalFollower, so this is an issue and your widget tree configuration is different and might remain different forever...

**Comment by fzyzcjy** [comment]
I agree. But an open source library maintainer has no time to fix each and every bug as he/she has full-time jobs to do.

**Comment by caleb654** [comment]
I also get the same issue when putting a text field inside a portal. I'm on the latest flutter stable version 3.0.1.

**Comment by caleb654** [comment]
I get the issue on macOS and web. Not sure if you have tried to reproduce it there.

**Comment by caleb654** [comment]
Just some added details to this issue. In web release mode it works fine. In debug though it throws an error.

**Comment by abhimanyupandian** [comment]
@caleb654 Came across the same issue with TextField inside the portal. But the EditableText widget works fine.

**Comment by runionke** [comment]
If you cut and paste the entire Modal example into a new project and swap out the Hello World Text with a TextField, it throws this error.

**Comment by angelareit** [comment]
I get this issue with a slider inside a portal entry as well.

**Comment by danielmahon** [comment]
I believe it has something to do with the default `Portal` placement trying to render a `TextField` or any other element that needs to be a child of `MaterialApp` or a `Scaffold`. For example moving `Portal` from above to under `MaterialApp` seems to solve the problem. Or like @ abhimanyupandian said, using `EditableText` which probably doesn't depend on as much also works.

**Comment by danielmahon** [comment]
@fzyzcjy on that note, can you show an example of properly using multiple portals? Seems to work inconsistently for me. My goal is to use a portal above the router that persists on navigation and another below that will transition with the page. Is that possible?

**Comment by fzyzcjy** [comment]
> can you show an example of properly using multiple portals?

I personally just put Portal and PortalTarget whenever I want it and has no problem...

I do have cases, when Portal 1 is above MaterialApp, and Portal 2 is under Scaffold.

**Comment by fzyzcjy** [comment]
Btw feel free to debug into the issue! Probably just create a reproducible sample, and use https://docs.flutter.dev/testing/code-debugging#layer-tree etc to dump all trees to see what is happening

**Comment by arualana** [comment]
Any update on this?

**Comment by fzyzcjy** [comment]
Feel free to reproduce and make a PR! I currently do not have much bandwidth on this since working on https://github.com/fzyzcjy/flutter_smooth

**Comment by lukepighetti** [comment]
My rule of thumb with open source packages I maintain is that if I have to suggest people contribute more than twice, it's time for me to schedule some time to fix it myself.

**Comment by fzyzcjy** [comment]
@lukepighetti I have just spent *a full month* (without holidays or rests) working on https://github.com/fzyzcjy/flutter_smooth, which "achieves ~60 FPS, no matter how heavy the tree is to build/layout", and have submitted (https://cjycode.com/flutter_smooth/insight/status) >30 PRs to Flutter framework and engine, and that one is quite hard because nobody (even googlers) thought that approach could work (but indeed it works after a month).

So please give me a bit time to rest (and finish remaining work of smooth) :)

**Comment by fzyzcjy** [comment]
@lukepighetti I have just spent *a full month* (without holidays or rests) working on https://github.com/fzyzcjy/flutter_smooth, which "achieves ~60 FPS, no matter how heavy the tree is to build/layout", and have submitted (https://cjycode.com/flutter_smooth/insight/status) >30 PRs to Flutter framework and engine, and that one is quite hard because everybody (even googlers) thought that approach would not work before (but indeed it works after a month). So please give me a bit time to rest (and finish remaining work of smooth) :) I do all open-source libraries completely for free.

**Comment by fzyzcjy** [comment]
As for the direction to solve this issue, I guess dumping the whole layer tree (and render object tree etc) on the minimal reproducible sample as well as some logging may help.

**Comment by roman-petrov** [comment]
> I'm having this issue with two PortalTargets (nested) when the visibility on the descendent changes from true to false
> 
> ```
> flutter: LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.
> flutter: 'package:flutter_portal/src/enhanced_composited_transform/flutter_src/rendering_layer.dart':
> flutter: Failed assertion: line 384 pos 7: '_debugCheckLeaderBeforeFollower(forwardLayers, inverseLayers)'
> ```

We  are getting exactly the same issue with nested `PortalTarget`. We are trying to show/hide portal based tooltip inside portal based popup window. We use `MouseRegion.onEnter` / `MouseRegion.onEnter` to show/hide tooltip.

I just found a workaround which solves the issue in our project.

Instead of doing 
```dart
PortalTarget(
  isVisible: <visibility>,
  child: <child>,
);
```

I am doing 

```dart
PortalTarget(
  child: Visibility(
    isVisible: <visibility>,
    child: <child>,
 ),
);
```

So this works for me for now, hope this helps somebody as a temporary workaround.
